name: Bug Report
description: File a bug report
labels: ["Pending"]
assignees:
  - Wutname1
body:
  - type: markdown
    attributes:
      value: |
        Please fillout the form below to submit your bug report.
  - type: input
    id: addon-version
    attributes:
      label: Addon Version
      description: What version of AdiBags did this error happen on?
      placeholder: v6.x.xx
    validations:
      required: true
  - type: dropdown
    id: wowversion
    attributes:
      label: World of Warcraft Version
      description: What World of Warcraft version did this happen on?
      options:
        - Retail
        - Retail PTR
        - Retail Beta
        - Wrath
        - Wrath PTR
        - TBC
        - Classic
        - Classic PTR
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of what the bug is, and include any stacktraces.
      placeholder: When opening...
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can I reproduce this issue so we can fix it?
      placeholder: 1. Click the minimap while jumping
